sudo: false
language: node_js
node_js:
  - "0.10"
  - "4.0"
  - "4.1"
  - "stable"
after_success:
  - if [ $TRAVIS_NODE_VERSION = '0.10' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ];
